trigger:
- dev_env

stages:
- stage: DeployRunbook
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: deploy_runbooks
    displayName: 'Deploy Runbooks'
    steps:
      - task: PowerShell@2
        displayName: 'Connecting to Azure'
        inputs:
          targetType: 'inline'
          script: ./scripts/run.ps1 -ConnectAzure -ResourceGroupName $(ResourceGroupName) -ServicePrincipalName $(ServicePrincipalName) -ServicePrincipalPass $(ServicePrincipalPass) -SubscriptionId $(SubscriptionId) -TenantId $(TenantId) -Verbose
      - task: PowerShell@2
        displayName: 'Deploying Runbooks'
        inputs:
          targetType: 'inline'
          script: ./scripts/run.ps1 -ConnectAzure -DeployRunbooks -RepoURL $(RepoURL) -SourceControlType $(SourceControlType) -SourceControlBranch $(SourceControlBranch) -RepoAccessToken $(RepoAccessToken) -ResourceGroupName $(ResourceGroupName) -AutomationAccountName $(AutomationAccountName) -Verbose